services:
  - type: web
    name: anwariya-backend-prototype
    env: docker
    plan: free

    dockerfilePath: backend/Dockerfile
    dockerContext: backend

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      # IMPORTANT: absolute path for sqlite inside container
      - key: DATABASE_URL
        value: "sqlite:////app/data/app.db"

    disk:
      name: anwariya-data
      mountPath: /app/data
      sizeGB: 1
